/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as ExternalRouteImport } from './routes/external'
import { Route as FullCheckupRouteImport } from './routes/full-checkup'
import { Route as SiteHealthRouteImport } from './routes/site-health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalRoute = ExternalRouteImport.update({
  id: '/external',
  path: '/external',
  getParentRoute: () => rootRouteImport,
} as any)
const FullCheckupRoute = FullCheckupRouteImport.update({
  id: '/full-checkup',
  path: '/full-checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteHealthRoute = SiteHealthRouteImport.update({
  id: '/site-health',
  path: '/site-health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/external': typeof ExternalRoute
  '/full-checkup': typeof FullCheckupRoute
  '/site-health': typeof SiteHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/external': typeof ExternalRoute
  '/full-checkup': typeof FullCheckupRoute
  '/site-health': typeof SiteHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/external': typeof ExternalRoute
  '/full-checkup': typeof FullCheckupRoute
  '/site-health': typeof SiteHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$section' | '/external' | '/full-checkup' | '/site-health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$section' | '/external' | '/full-checkup' | '/site-health'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/external'
    | '/full-checkup'
    | '/site-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  ExternalRoute: typeof ExternalRoute
  FullCheckupRoute: typeof FullCheckupRoute
  SiteHealthRoute: typeof SiteHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external': {
      id: '/external'
      path: '/external'
      fullPath: '/external'
      preLoaderRoute: typeof ExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-checkup': {
      id: '/full-checkup'
      path: '/full-checkup'
      fullPath: '/full-checkup'
      preLoaderRoute: typeof FullCheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-health': {
      id: '/site-health'
      path: '/site-health'
      fullPath: '/site-health'
      preLoaderRoute: typeof SiteHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  ExternalRoute: ExternalRoute,
  FullCheckupRoute: FullCheckupRoute,
  SiteHealthRoute: SiteHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
